### ISSUE TITLE
Unable to add some labels

### ISSUE THREAD

**Issue by cseaayush** [Ashton-Sidhu/plotly-graph#1]
I really appreciate your work on visualization  network graph, Please can you help me in below points

How to resize the arrows as they are small in directed graph

How to add label on nodes (Not on hover but actual Label) Same with edges.

Can we add sub nodes like expanding like a process tree

**Comment by Ashton-Sidhu** [comment]
Hey thanks for reporting this! I'll be releasing an update with the next day or 2 addressing issues 1&2.

At this time there is no plan to add the interactive ability to view sub nodes. You can always create a subgraph from a node and then view the subgraph.

**Comment by cseaayush** [comment]
Thanks a lot also can you please add hover text on edges (like custom text) not the from and to node text

**Comment by cseaayush** [comment]
Hi This node_label="", ( e.g node_label="label",) here label is a list so it is applying to all nodes same text but i need like label[0] = "abc" to one node and label[1]= "xyz" to other node and so on. I don't know how to do that can you please help

**Comment by Ashton-Sidhu** [comment]
> 
> 
> Thanks a lot also can you please add hover text on edges (like custom text) not the from and to node text

If you have any edge properties, you can set the property `hoveredge_text = True`

**Comment by Ashton-Sidhu** [comment]
> 
> 
> Hi This node_label="", ( e.g node_label="label",) here label is a list so it is applying to all nodes same text but i need like label[0] = "abc" to one node and label[1]= "xyz" to other node and so on. I don't know how to do that can you please help

Best way to do it would be to use `nx.set_node_attributes` to set an attribute for each node with the text you want to be associated with each node. Then I would set `node_label=your_attribute` to display the label. As of right now there is no custom labelling but I might add it in the upcoming release.

**Comment by Ashton-Sidhu** [comment]
Pushed a new release that addresses issues 1&2
