### ISSUE TITLE
Suggestion: change Python version cap to "python >=3.8, <4.0" and remove version caps on dependencies, e.g. "pandas >= 1.4.3"

### ISSUE THREAD

**Issue by araichev** [Ashton-Sidhu/plotly-graph#14]
It will make your library easier to install; cf https://iscinumpy.dev/post/bound-version-constraints/ .
For example, i couldn't install your library in my project, because your Python bound conflicts with mine ("python >=3.8, <4.0").
Then when i change my python bound, your package downgrades several of my project's dependencies, e.g.

Package operations: 1 install, 3 updates, 0 removals

  • Updating jupyterlab-widgets (3.0.3 -> 1.1.1)
  • Updating widgetsnbextension (4.0.3 -> 3.6.1)
  • Updating ipywidgets (8.0.2 -> 7.7.2)
  • Installing igviz (0.5.0)

**Comment by Ashton-Sidhu** [comment]
There were some issues with compatibility issues with `plotly` and the latest version if `ipywidgets`. I will see if those are resolved and then update the versions.

With regards to python constraints, Python 3.7 end of life is in June 2023 so having a minimum of 3.8 is something I did to make this project easier to maintain and to keep up to date. I probably won't be changing this aspect of it.

**Comment by araichev** [comment]
Thanks for your attention @Ashton-Sidhu .
In general, i echo the article i linked to above and suggest removing the version upper bounds from your library's dependencies, because they will cause downstream problems for users of your library.
For example, instead of `ipywidgets = "^7.7.1"`, use `ipywidgets = ">=7.7.1"`

**Comment by Ashton-Sidhu** [comment]
Thank you for raising this issue, I read the article again + some supplementary readings coupled with looking at other libraries and I will be going through each of the dependencies and removing the version upper bounds.

Learned something new here!

Will make a release in the coming week with the removed upper bounds, thanks again !

**Comment by araichev** [comment]
Good to hear @Ashton-Sidhu .
I too have often found open source projects to be great learning experiences.
