### ISSUE TITLE
Incorrect edge text

### ISSUE THREAD

**Issue by nguyen14ck** [Ashton-Sidhu/plotly-graph#15]
File "ig.viz.py", line 339:
```
                    edge_properties[edge_pair][prop] += [edge[2][prop]]
```
should have 1 more tab at the beginning of line.

**Comment by Ashton-Sidhu** [comment]
Thanks for the issue, will fix this !

**Comment by Ashton-Sidhu** [comment]
This has been resolved, will put out a release in the coming week !
