### ISSUE TITLE
removing the white lines around the nodes

### ISSUE THREAD

**Issue by nettanetta** [Ashton-Sidhu/plotly-graph#3]
Hi!
first of all, thank you, I really like igviz and use it a lot.
Is it possible to remove the white line around the nodes? or replace them with a line of the same color of the node itself? 
thanks!
Netta

**Comment by Ashton-Sidhu** [comment]
Hey @nettanetta thanks for the issue, sorry for taking so long - picking up this project again. This feature will be in the next release coming soon !

**Comment by Ashton-Sidhu** [comment]
This is fixed in the latest release !
